version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: "Update System"
          command: |
            set -x
            sudo apt-get update
            sudo apt-get install make python3-pip
      - run:
          name: "Install Poetry"
          command: |
            set -x
            pip3 install poetry
            poetry install
            make tox
