version: 2.1
workflows:
  version: 2
  build-and-scan:
    jobs:
      - build-code
      - scan

jobs:
  build-code:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: "Update System"
          command: |
            set -x
            sudo apt-get update
            sudo apt-get install make python3-pip
      - run:
          name: "Run tox"
          command: |
            set -x
            pip3 install poetry
            poetry install
            poetry run tox

  scan:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install trivy"
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: "Build Docker local Image"
          command: |
            docker build -t trivy-ci-test:${CIRCLE_SHA1} .
      - run:
          name: "Scan the local image with trivy"
          command: trivy image --exit-code 0 --no-progress trivy-ci-test:${CIRCLE_SHA1}
      - run:
          name: "Scan the project with trivy"
          command: trivy repo --exit-code 0 --no-progress https://github.com/yriveiro/giu
